spring:
  application:
    name: noted

  datasource:
    url: jdbc:h2:file:./data/noteddb
    driverClasssName: org.h2.Driver
    username: user
    password: ''

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-suto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

